[package]
name = "finianceable"
version = "0.1.0"
edition = "2024"

[dependencies]
pyo3 = { version = "0.20" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[package.metadata.pyo3]
python = "C:\\Projects\\Finianceable\\env\\Scripts\\python.exe"